name = "SatelliteToolboxGravityModels"
uuid = "bd9e9728-6f7b-4d28-9e50-c765cb1b7c8c"
license = "MIT"
desc = "Gravity models."
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]
version = "1.3.0"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
ReferenceFrameRotations = "74f56ac7-18b3-5285-802d-d4bd4f104033"
SatelliteToolboxBase = "9e17983a-0463-41a7-9a16-1682db6d8b66"
SatelliteToolboxLegendre = "7fa26607-a272-47b2-9aa2-a6c1d419d9d2"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[extensions]
SatelliteToolboxGravityModelsZygoteExt = ["ForwardDiff", "Zygote"]

[compat]
Crayons = "4"
Dates = "1.10"
Downloads = "1"
ForwardDiff = "1.0"
ReferenceFrameRotations = "3.1"
SatelliteToolboxBase = "1.1"
SatelliteToolboxLegendre = "1.1"
Scratch = "1"
StaticArrays = "1"
Zygote = "0.6, 0.7"
julia = "1.10, 1.11, 1.12"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SatelliteToolboxTransformations = "6b019ec1-7a1e-4f04-96c7-a9db1ca5514d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DelimitedFiles", "LinearAlgebra", "Pkg", "SatelliteToolboxTransformations"]
